### ISSUE TITLE
Unsupported filetype for valid image using geturl.php

### ISSUE THREAD

**Issue by dessalines** [HaschekSolutions/pictshare#108]
Could you help me test this seemingly valid image with geturl.php?

https://MY_PICTSHARE.com/pictshare/api/geturl.php?url=https://i.guim.co.uk/img/media/4d908693e566fdd7f8cdeac559f6375b739887a3/356_37_3264_1958/master/3264.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=3a70177dcc60673c606302d96fcbd9bc

Error:

```
filetype: "x-empty"
reason: "Unsupported filetype"
status: "err"
```
​

**Comment by chrisiaut** [comment]
are you using the docker container or did you install it yourself?

If it's the latter it looks like you're missing some libraries.. does the server have the `file` command?

**Comment by dessalines** [comment]
Its using shtripok's docker (necessary for arm compatibility too I think). My `docker-compose.yml` section: 

```
  pictshare:
    image: shtripok/pictshare:latest
    ports:
      - "127.0.0.1:8537:80"
    volumes:
      - pictshare:/usr/share/nginx/html/data
    restart: always
```

Did you test this one out?
