### ISSUE TITLE
api/upload not return full URL

### ISSUE THREAD

**Issue by changchichung** [HaschekSolutions/pictshare#129]
I run pictshare with docker-compose
docker-compose.yml
```
version: '3.3'

services:
  pictshare:
    image: hascheksolutions/pictshare:latest
    ports:
      - "804:80"
    volumes:
      - pictshare:/usr/share/nginx/html/data
volumes:
  pictshare:
```

upload file in command prompt
```
chchang@hqdc039:~/docker/pictshare$ curl -F "file=@docker-compose.yml" "http://192.168.11.39:804/api/upload.php"
{"status":"ok","hash":"foyvnl.txt","filetype":"text","url":"foyvnl.txt"}
chchang@hqdc039:~/docker/pictshare$ 
```
in document , API section , the command should return full URL like
http://192.168.11.39:804/fovnl.txt"
but it doesn't.

any suggestions ??
